export const fingers = [
  { name: 'left pinky', color: 'bg-yellow-400' },
  { name: 'left ring', color: 'bg-green-400' },
  { name: 'left middle', color: 'bg-red-400' },
  { name: 'left index', color: 'bg-blue-400' },
  { name: 'right index', color: 'bg-blue-400' },
  { name: 'right middle', color: 'bg-red-400' },
  { name: 'right ring', color: 'bg-green-400' },
  { name: 'right pinky', color: 'bg-yellow-400' },
];

export const codingKeys = [
  { key: '[', shift: false, finger: 'right pinky' },
  { key: ']', shift: false, finger: 'right pinky' },
  { key: ';', shift: false, finger: 'right pinky' },
  { key: "'", shift: false, finger: 'right pinky' },
  { key: '/', shift: false, finger: 'right pinky' },
  { key: '\\', shift: false, finger: 'right pinky' },
  { key: '{', shift: true, finger: 'right pinky' },
  { key: '}', shift: true, finger: 'right pinky' },
  { key: ':', shift: true, finger: 'right pinky' },
  { key: '"', shift: true, finger: 'right pinky' },
  { key: '|', shift: true, finger: 'right pinky' },
  { key: '<', shift: true, finger: 'right middle' },
  { key: '>', shift: true, finger: 'right ring' },
  { key: '?', shift: true, finger: 'right pinky' },
  { key: '~', shift: true, finger: 'left pinky' },
  { key: '`', shift: true, finger: 'left pinky' },
  { key: '!', shift: true, finger: 'left pinky' },
  { key: '@', shift: true, finger: 'left ring' },
  { key: '#', shift: true, finger: 'left middle' },
  { key: '$', shift: true, finger: 'left index' },
  { key: '%', shift: true, finger: 'left index' },
  { key: '^', shift: true, finger: 'right index' },
  { key: '&', shift: true, finger: 'right index' },
  { key: '*', shift: true, finger: 'right middle' },
  { key: '(', shift: true, finger: 'right ring' },
  { key: ')', shift: true, finger: 'right pinky' },
  { key: '-', shift: false, finger: 'right pinky' },
  { key: '_', shift: true, finger: 'right pinky' },
  { key: '+', shift: true, finger: 'right pinky' },
  { key: '=', shift: false, finger: 'right pinky' },
  { key: '.', shift: false, finger: 'right ring' },
  { key: ',', shift: false, finger: 'right middle' },
];
